"""为 DB15K 电影实体生成中文别名，写入 db15k_movie_lexicon.json。

运行方式：cd D:\\AI\\MovieHub && python backend/scripts/generate_zh_aliases.py
"""
import json
import os

# ============================================================
# 已知电影的中文翻译（覆盖最常见的 ~400 部）
# ============================================================
KNOWN_ZH = {
    # === 经典高分 ===
    "The_Shawshank_Redemption": "肖申克的救赎",
    "The_Godfather": "教父",
    "The_Dark_Knight": "蝙蝠侠：黑暗骑士",
    "The_Godfather_Part_II": "教父2",
    "Schindler's_List": "辛德勒的名单",
    "Pulp_Fiction": "低俗小说",
    "Forrest_Gump": "阿甘正传",
    "Inception": "盗梦空间",
    "The_Matrix": "黑客帝国",
    "Star_Wars": "星球大战",
    "The_Lord_of_the_Rings": "指环王",
    "Titanic_(1997_film)": "泰坦尼克号",
    "Avatar_(2009_film)": "阿凡达",
    "Gladiator_(2000_film)": "角斗士",
    "Braveheart": "勇敢的心",
    "Saving_Private_Ryan": "拯救大兵瑞恩",
    "The_Silence_of_the_Lambs_(film)": "沉默的羔羊",
    "The_Pianist_(2002_film)": "钢琴家",
    "The_Green_Mile_(film)": "绿里奇迹",
    "Jurassic_Park_(film)": "侏罗纪公园",
    "Spirited_Away": "千与千寻",

    # === 科幻/动作 ===
    "Alien_(film)": "异形",
    "Aliens_(film)": "异形2",
    "Alien_vs._Predator_(film)": "异形大战铁血战士",
    "Terminator": "终结者",
    "Terminator_2:_Judgment_Day": "终结者2：审判日",
    "Blade_Runner": "银翼杀手",
    "Total_Recall_(2012_film)": "全面回忆",
    "Minority_Report_(film)": "少数派报告",
    "I,_Robot_(film)": "我，机器人",
    "I_Am_Legend_(film)": "我是传奇",
    "Independence_Day_(1996_film)": "独立日",
    "Armageddon_(1998_film)": "世界末日",
    "Deep_Impact_(film)": "天地大冲撞",
    "The_Island_(2005_film)": "逃出克隆岛",
    "Sunshine_(1999_film)": "太阳浩劫",
    "Moonraker_(film)": "太空城",
    "Star_Trek_(film)": "星际迷航",
    "Star_Wars:_The_Clone_Wars_(film)": "星球大战：克隆战争",
    "Stargate_(film)": "星际之门",
    "Starship_Troopers_(film)": "星船伞兵",
    "Dune_(film)": "沙丘",
    "Looper_(film)": "环形使者",
    "Jumper_(2008_film)": "心灵传输者",
    "Super_8_(film)": "超级八",
    "Prometheus_(2012_film)": "普罗米修斯",
    "Man_of_Steel": "超人：钢铁之躯",
    "Iron_Man_(2008_film)": "钢铁侠",
    "The_Incredible_Hulk_(film)": "无敌浩克",
    "Thor_(film)": "雷神",
    "The_Avengers_(2012_film)": "复仇者联盟",
    "Spider-Man_(2002_film)": "蜘蛛侠",
    "The_Amazing_Spider-Man_(2012_film)": "超凡蜘蛛侠",
    "X-Men_(film)": "X战警",
    "X2_(film)": "X战警2",
    "Fantastic_Four_(2005_film)": "神奇四侠",
    "Daredevil_(film)": "超胆侠",
    "Hulk_(film)": "绿巨人浩克",
    "Hellboy_(film)": "地狱男爵",
    "Green_Lantern_(film)": "绿灯侠",
    "Catwoman_(film)": "猫女",
    "Elektra_(2005_film)": "艾丽卡",
    "Ghost_Rider": "恶灵骑士",
    "Watchmen_(film)": "守望者",
    "V_for_Vendetta_(film)": "V字仇杀队",
    "300_(film)": "300勇士",
    "Immortals_(2011_film)": "惊天战神",
    "Clash_of_the_Titans_(2010_film)": "诸神之战",
    "Troy_(film)": "特洛伊",
    "Alexander_(2004_film)": "亚历山大大帝",
    "Kingdom_of_Heaven_(film)": "天国王朝",
    "Glory_(1989_film)": "光荣战役",
    "The_Patriot_(2000_film)": "爱国者",
    "Black_Hawk_Down_(film)": "黑鹰坠落",
    "Platoon_(film)": "野战排",
    "Full_Metal_Jacket": "全金属外壳",
    "Apocalypse_Now": "现代启示录",
    "The_Deer_Hunter": "猎鹿人",
    "Born_on_the_Fourth_of_July_(film)": "生于七月四日",
    "We_Were_Soldiers": "我们曾是战士",
    "Pearl_Harbor_(film)": "珍珠港",
    "Midway": "中途岛战役",
    "Tora!_Tora!_Tora!": "虎！虎！虎！",
    "The_Longest_Day_(film)": "最长的一天",
    "A_Bridge_Too_Far_(film)": "遥远的桥",
    "The_Guns_of_Navarone_(film)": "纳瓦隆大炮",
    "Where_Eagles_Dare": "血染雪山堡",
    "The_Great_Escape": "大逃亡",
    "Patton_(film)": "巴顿将军",
    "MacArthur": "麦克阿瑟",

    # === 悬疑/犯罪 ===
    "Se7en_(film)": "七宗罪",
    "Zodiac_(film)": "十二宫",
    "The_Silence_of_the_Lambs_(film)": "沉默的羔羊",
    "Hannibal_(film)": "汉尼拔",
    "Hannibal_Rising_(film)": "少年汉尼拔",
    "Red_Dragon_(film)": "红龙",
    "Psycho_(1960_film)": "惊魂记",
    "Psycho_(1998_film)": "惊魂记",
    "The_Birds_(film)": "群鸟",
    "Rear_Window": "后窗",
    "Vertigo_(film)": "迷魂记",
    "North_by_Northwest": "西北偏北",
    "Dial_M_for_Murder": "电话谋杀案",
    "Rope_(film)": "夺魂索",
    "The_Man_Who_Knew_Too_Much_(1956_film)": "擒凶记",
    "Foreign_Correspondent_(film)": "海外特派员",
    "Saboteur_(film)": "海角擒凶",
    "Chinatown_(1974_film)": "唐人街",
    "L.A._Confidential_(film)": "洛城机密",
    "The_Maltese_Falcon_(1941_film)": "马耳他之鹰",
    "Casablanca_(film)": "卡萨布兰卡",
    "The_French_Connection_(film)": "法国贩毒网",
    "Serpico": "冲突",
    "Dog_Day_Afternoon": "炎热的下午",
    "Heat_(1995_film)": "盗火线",
    "The_Usual_Suspects": "非常嫌疑犯",
    "Memento_(film)": "记忆碎片",
    "Insomnia": "失眠症",
    "Primal_Fear_(film)": "一级恐惧",
    "The_Sixth_Sense": "第六感",
    "Unbreakable": "不死劫",
    "Signs_(film)": "天兆",
    "The_Village_(2004_film)": "神秘村",
    "The_Happening_(2008_film)": "灭顶之灾",
    "Shutter_Island_(film)": "禁闭岛",
    "Gone_Girl": "消失的爱人",
    "The_Girl_with_the_Dragon_Tattoo_(2011_film)": "龙纹身的女孩",
    "The_Girl_with_the_Dragon_Tattoo_(2009_film)": "龙纹身的女孩",
    "Mystic_River_(film)": "神秘河",
    "No_Country_for_Old_Men_(film)": "老无所依",
    "Blood_Diamond_(film)": "血钻",
    "The_Departed": "无间行者",
    "Infernal_Affairs": "无间道",
    "Jackie_Brown_(film)": "危险关系",
    "Kill_Bill:_Volume_1": "杀死比尔",
    "Kill_Bill:_Volume_2": "杀死比尔2",
    "Sin_City_(film)": "罪恶之城",
    "From_Hell_(film)": "来自地狱",
    "Sleepy_Hollow_(film)": "断头谷",
    "Saw_(2004_film)": "电锯惊魂",
    "Hostel": "人皮客栈",
    "The_Texas_Chainsaw_Massacre_(2003_film)": "德州电锯杀人狂",
    "Halloween_(1978_film)": "月光光心慌慌",
    "Halloween_(2007_film)": "月光光心慌慌",
    "Friday_the_13th": "十三号星期五",
    "A_Nightmare_on_Elm_Street": "猛鬼街",
    "Scream": "惊声尖叫",
    "I_Know_What_You_Did_Last_Summer": "我知道你去年夏天干了什么",
    "Final_Destination_(film)": "死神来了",
    "The_Ring_(2002_film)": "午夜凶铃",
    "The_Exorcist_(film)": "驱魔人",
    "Rosemary's_Baby_(film)": "罗斯玛丽的婴儿",
    "Poltergeist_(1982_film)": "鬼驱人",
    "The_Others_(2001_film)": "小岛惊魂",
    "The_Orphanage_(film)": "孤儿院",
    "Insidious_(film)": "潜伏",
    "The_Conjuring": "招魂",
    "Sinister": "险恶",
    "Paranormal_Activity": "灵动：鬼影实录",

    # === 喜剧 ===
    "The_Hangover": "宿醉",
    "Bridesmaids_(2011_film)": "伴娘",
    "Superbad_(film)": "超级坏",
    "Pineapple_Express_(film)": "菠萝快递",
    "Knocked_Up": "一夜大肚",
    "The_40-Year-Old_Virgin": "四十岁的老处男",
    "Anchorman": "王牌播音员",
    "Step_Brothers_(film)": "非亲兄弟",
    "Talladega_Nights": "塔拉迪加之夜",
    "Old_School": "留级之王",
    "Road_Trip_(film)": "公路之旅",
    "American_Pie_(film)": "美国派",
    "Eurotrip": "欧洲任我行",
    "Harold_&_Kumar": "哈罗德与库玛",
    "Dumb_and_Dumber": "阿呆与阿瓜",
    "The_Mask_(film)": "变相怪杰",
    "Ace_Ventura:_Pet_Detective": "神探飞机头",
    "Liar_Liar": "大话王",
    "Bruce_Almighty": "冒牌天神",
    "The_Truman_Show": "楚门的世界",
    "Groundhog_Day_(film)": "偷天情缘",
    "Click_(2006_film)": "人生遥控器",
    "Bedtime_Stories_(film)": "睡前故事",
    "Grown_Ups_(film)": "长大成人",
    "Jack_and_Jill_(2011_film)": "杰克与吉尔",
    "That's_My_Boy_(2012_film)": "这就是我的男孩",
    "Yes_Man_(film)": "好好先生",
    "The_Dictator_(2012_film)": "独裁者",
    "Borat": "波拉特",
    "Bruno": "布鲁诺",
    "Ted_(film)": "泰迪熊",
    "Paul_(film)": "保罗",
    "Wayne's_World_(film)": "反斗智多星",
    "Bill_&_Ted's_Excellent_Adventure": "比尔和泰德历险记",
    "Clerks": "疯狂店员",
    "Chasing_Amy": "追逐艾米",
    "Jay_and_Silent_Bob_Strike_Back": "白烂贱客",
    "Zoolander": "名模大间谍",
    "Dodgeball": "躲避球",
    "Anchorman:_The_Legend_of_Ron_Burgundy": "王牌播音员",
    "Tropic_Thunder": "热带惊雷",
    "Zombieland": "丧尸乐园",
    "Shaun_of_the_Dead": "僵尸肖恩",
    "Hot_Fuzz": "热血警探",
    "The_World's_End": "世界尽头",
    "Scott_Pilgrim_vs._the_World": "歪小子斯科特",
    "Juno_(film)": "朱诺",
    "Little_Miss_Sunshine": "阳光小美女",
    "Napoleon_Dynamite": "大人物拿破仑",
    "Rushmore_(film)": "都是爱情惹的祸",
    "The_Royal_Tenenbaums": "特伦鲍姆一家",
    "The_Life_Aquatic_with_Steve_Zissou": "水中生活",
    "Fantastic_Mr._Fox_(film)": "了不起的狐狸爸爸",
    "Moonrise_Kingdom": "月升王国",

    # === 爱情/剧情 ===
    "The_Notebook": "恋恋笔记本",
    "P.S._I_Love_You_(film)": "附注：我爱你",
    "Love_Actually": "真爱至上",
    "Notting_Hill_(film)": "诺丁山",
    "Bridget_Jones's_Diary_(film)": "BJ单身日记",
    "The_Vow_(2012_film)": "誓约",
    "Dear_John": "分手信",
    "A_Walk_to_Remember": "初恋的回忆",
    "The_Time_Traveler's_Wife": "时间旅行者的妻子",
    "Twilight_(2008_film)": "暮光之城",
    "The_Little_Mermaid_(1989_film)": "小美人鱼",
    "Beauty_and_the_Beast_(1991_film)": "美女与野兽",
    "Aladdin": "阿拉丁",
    "The_Lion_King": "狮子王",
    "Mulan_(1998_film)": "花木兰",
    "Pocahontas_(1995_film)": "风中奇缘",
    "Tarzan_(1999_film)": "泰山",
    "Hercules_(1997_film)": "大力士",
    "Cinderella_(1950_film)": "灰姑娘",
    "Snow_White_and_the_Seven_Dwarfs_(1937_film)": "白雪公主",
    "Pinocchio_(1940_film)": "匹诺曹",
    "Bambi": "小鹿斑比",
    "Dumbo": "小飞象",
    "Peter_Pan_(2003_film)": "小飞侠",
    "Alice_in_Wonderland_(2010_film)": "爱丽丝梦游仙境",
    "Alice_in_Wonderland_(1951_film)": "爱丽丝梦游仙境",
    "Sleeping_Beauty": "睡美人",
    "The_Jungle_Book": "森林王子",
    "The_Aristocats": "猫儿历险记",
    "Robin_Hood_(1973_film)": "罗宾汉",
    "The_Rescuers": "救难小英雄",
    "Oliver_&_Company": "奥丽华历险记",
    "The_Hunchback_of_Notre_Dame_(1996_film)": "钟楼怪人",
    "Enchanted_(film)": "魔法奇缘",
    "Bolt_(2008_film)": "闪电狗",
    "Tangled": "魔发奇缘",
    "Brave_(2012_film)": "勇敢传说",
    "Wreck-It_Ralph": "无敌破坏王",
    "Frozen": "冰雪奇缘",
    "Big_Hero_6": "超能陆战队",
    "Inside_Out": "头脑特工队",
    "Zootopia": "疯狂动物城",
    "Moana": "海洋奇缘",
    "Coco": "寻梦环游记",
    "Toy_Story": "玩具总动员",
    "A_Bug's_Life": "虫虫特工队",
    "Monsters,_Inc.": "怪兽电力公司",
    "Finding_Nemo": "海底总动员",
    "The_Incredibles": "超人总动员",
    "Cars_(film)": "汽车总动员",
    "Ratatouille_(film)": "美食总动员",
    "WALL-E": "机器人总动员",
    "Up_(2009_film)": "飞屋环游记",
    "How_to_Train_Your_Dragon_(film)": "驯龙高手",
    "Kung_Fu_Panda": "功夫熊猫",
    "Madagascar_(2005_film)": "马达加斯加",
    "Shrek": "怪物史瑞克",
    "Ice_Age_(2002_film)": "冰河世纪",
    "Robots_(2005_film)": "机器人历险记",
    "Happy_Feet": "快乐的大脚",
    "Surf's_Up": "冲浪企鹅",
    "Despicable_Me": "神偷奶爸",
    "The_Lorax_(film)": "老雷斯的故事",
    "Dr._Seuss'_The_Cat_in_the_Hat_(film)": "戴帽子的猫",
    "Horton_Hears_a_Who!": "霍顿与无名氏",
    "Rio": "里约大冒险",
    "Epic": "森林战士",
    "The_Croods": "疯狂原始人",
    "Turbo": "极速蜗牛",
    "Mr._Peabody_&_Sherman": "天才眼镜狗",
    "Home_(2015_film)": "疯狂外星人",
    "The_Smurfs_(film)": "蓝精灵",
    "Alvin_and_the_Chipmunks": "鼠来宝",
    "Garfield_(film)": "加菲猫",
    "Scooby-Doo_(film)": "史酷比",
    "The_Flintstones_(film)": "摩登原始人",
    "Astro_Boy_(film)": "阿童木",

    # === 惊悚/冒险 ===
    "Inception_(2010_film)": "盗梦空间",
    "The_Prestige_(film)": "致命魔术",
    "The_Dark_Knight_Rises": "蝙蝠侠：黑暗骑士崛起",
    "Batman_Begins": "蝙蝠侠：侠影之谜",
    "Batman_(1989_film)": "蝙蝠侠",
    "Batman_&_Robin_(film)": "蝙蝠侠与罗宾",
    "Superman_(1978_film)": "超人",
    "Superman_Returns": "超人归来",
    "The_Fast_and_the_Furious_(2001_film)": "速度与激情",
    "2_Fast_2_Furious": "速度与激情2",
    "The_Bourne_Identity_(2002_film)": "谍影重重",
    "The_Bourne_Supremacy_(film)": "谍影重重2",
    "The_Bourne_Ultimatum_(film)": "谍影重重3",
    "The_Bourne_Legacy_(film)": "谍影重重4",
    "Mission:_Impossible_(film)": "碟中谍",
    "Casino_Royale_(2006_film)": "007：大战皇家赌场",
    "Casino_Royale_(1967_film)": "007：皇家赌场",
    "Dr._No_(film)": "007：诺博士",
    "From_Russia_with_Love_(film)": "007：来自俄罗斯的爱情",
    "Goldfinger_(film)": "007：金手指",
    "Thunderball_(film)": "007：霹雳弹",
    "You_Only_Live_Twice_(film)": "007：雷霆谷",
    "On_Her_Majesty's_Secret_Service_(film)": "007：女王密使",
    "Diamonds_Are_Forever_(film)": "007：金刚钻",
    "Live_and_Let_Die_(film)": "007：生死关头",
    "The_Man_with_the_Golden_Gun_(film)": "007：金枪人",
    "The_Spy_Who_Loved_Me_(film)": "007：海底城",
    "For_Your_Eyes_Only_(film)": "007：最高机密",
    "Octopussy": "007：八爪女",
    "The_Living_Daylights": "007：黎明生机",
    "Licence_to_Kill": "007：杀人执照",
    "GoldenEye": "007：黄金眼",
    "Tomorrow_Never_Dies": "007：明日帝国",
    "The_World_Is_Not_Enough": "007：黑日危机",
    "Die_Another_Day": "007：择日而亡",

    # === 灾难/冒险 ===
    "Twister_(1996_film)": "龙卷风",
    "The_Day_After_Tomorrow": "后天",
    "2012_(film)": "2012",
    "Volcano": "活火熔城",
    "Dante's_Peak": "天崩地裂",
    "Earthquake": "大地震",
    "The_Towering_Inferno": "火烧摩天楼",
    "The_Poseidon_Adventure_(1972_film)": "海神号",
    "Jaws_(film)": "大白鲨",
    "Anaconda_(film)": "狂蟒之灾",
    "Deep_Blue_Sea": "深海狂鲨",
    "King_Kong_(2005_film)": "金刚",
    "King_Kong_(1933_film)": "金刚",
    "Godzilla_(1998_film)": "哥斯拉",
    "Mighty_Joe_Young_(1998_film)": "巨猩乔扬",
    "Jurassic_Park_(film)": "侏罗纪公园",
    "The_Lost_World:_Jurassic_Park": "侏罗纪公园2：失落的世界",
    "Jurassic_Park_III": "侏罗纪公园3",
    "Journey_to_the_Center_of_the_Earth": "地心游记",
    "Around_the_World_in_80_Days_(2004_film)": "环游世界八十天",
    "Around_the_World_in_80_Days_(1956_film)": "环游世界八十天",
    "The_Time_Machine_(2002_film)": "时间机器",
    "War_of_the_Worlds_(2005_film)": "世界大战",
    "The_Hitchhiker's_Guide_to_the_Galaxy_(film)": "银河系漫游指南",
    "John_Carter_(film)": "异星战场",
    "Prince_of_Persia:_The_Sands_of_Time_(film)": "波斯王子：时之刃",
    "The_Mummy_(1999_film)": "木乃伊",
    "The_Scorpion_King": "蝎子王",
    "Van_Helsing_(film)": "范海辛",
    "National_Treasure_(film)": "国家宝藏",
    "The_Da_Vinci_Code_(film)": "达芬奇密码",
    "Angels_&_Demons_(film)": "天使与魔鬼",
    "The_Lost_Weekend_(film)": "失去的周末",

    # === 剧情/文艺 ===
    "American_Beauty_(1999_film)": "美国丽人",
    "A_Beautiful_Mind_(film)": "美丽心灵",
    "Good_Will_Hunting": "心灵捕手",
    "Dead_Poets_Society": "死亡诗社",
    "The_Dead_Poets_Society": "死亡诗社",
    "One_Flew_Over_the_Cuckoo's_Nest_(film)": "飞越疯人院",
    "The_Shining_(film)": "闪灵",
    "Eyes_Wide_Shut": "大开眼戒",
    "Full_Metal_Jacket_(film)": "全金属外壳",
    "2001:_A_Space_Odyssey_(film)": "2001太空漫游",
    "A_Clockwork_Orange_(film)": "发条橙",
    "Barry_Lyndon": "乱世儿女",
    "Spartacus_(film)": "斯巴达克斯",
    "Ben-Hur_(1959_film)": "宾虚",
    "The_Ten_Commandments_(1956_film)": "十诫",
    "Lawrence_of_Arabia_(film)": "阿拉伯的劳伦斯",
    "Doctor_Zhivago_(film)": "日瓦戈医生",
    "Gone_with_the_Wind_(film)": "乱世佳人",
    "The_Wizard_of_Oz_(1939_film)": "绿野仙踪",
    "Singin'_in_the_Rain": "雨中曲",
    "West_Side_Story_(film)": "西区故事",
    "The_Sound_of_Music_(film)": "音乐之声",
    "My_Fair_Lady_(film)": "窈窕淑女",
    "Oliver!_(film)": "雾都孤儿",
    "Fiddler_on_the_Roof_(film)": "屋顶上的小提琴手",
    "Grease_(film)": "油脂",
    "Chicago_(2002_film)": "芝加哥",
    "Moulin_Rouge!": "红磨坊",
    "Evita_(1996_film)": "贝隆夫人",
    "Mamma_Mia!_(film)": "妈妈咪呀",
    "Dreamgirls_(film)": "追梦女郎",
    "Ray_(film)": "灵魂歌王",
    "Walk_the_Line": "与歌同行",
    "Coal_Miner's_Daughter_(film)": "矿工的女儿",
    "La_Vie_en_rose_(film)": "玫瑰人生",
    "Control": "控制",
    "The_Doors": "大门",
    "The_Rose_(film)": "歌声泪影",
    "Amadeus_(film)": "莫扎特传",
    "Chaplin_(film)": "卓别林",
    "Ed_Wood_(film)": "艾德·伍德",
    "Man_on_the_Moon_(film)": "月亮上的人",
    "Iris_(2001_film)": "携手人生",
    "The_Hours_(film)": "时时刻刻",
    "The_Reader_(2008_film)": "朗读者",
    "The_English_Patient_(film)": "英国病人",
    "The_Painted_Veil_(2006_film)": "面纱",
    "Atonement_(film)": "赎罪",
    "Revolutionary_Road_(film)": "革命之路",
    "Blue_Velvet_(film)": "蓝丝绒",
    "Mulholland_Drive_(film)": "穆赫兰道",
    "Lost_Highway_(film)": "妖夜慌踪",
    "Wild_at_Heart_(film)": "我心狂野",
    "Eraserhead": "橡皮头",
    "The_Elephant_Man_(film)": "象人",
    "Dune_(film)": "沙丘",
    "Crash_(2004_film)": "撞车",
    "Crash_(1996_film)": "欲望号快车",
    "Babel_(film)": "通天塔",
    "21_Grams": "21克",
    "Amores_Perros": "爱情是狗娘",
    "The_Thin_Red_Line_(1998_film)": "细细的红线",
    "The_Tree_of_Life_(film)": "生命之树",
    "The_New_World_(2005_film)": "新世界",
    "Badlands": "荒漠情",
    "Days_of_Heaven": "天堂之日",
    "Magnolia_(film)": "木兰花",
    "Boogie_Nights": "不羁夜",
    "There_Will_Be_Blood": "血色将至",
    "The_Master_(2012_film)": "大师",
    "Punch-Drunk_Love": "狂野之爱",
    "Sideways": "杯酒人生",
    "The_Descendants": "后人",
    "Nebraska": "内布拉斯加",
    "About_Schmidt": "关于施密特",
    "Election_(1999_film)": "选举",
    "Lost_in_Translation_(film)": "迷失东京",
    "The_Virgin_Suicides_(film)": "处女之死",
    "Marie_Antoinette_(2006_film)": "绝代艳后",
    "Somewhere": "在某处",
    "The_Bling_Ring": "珠光宝气",

    # === 更多知名电影 ===
    "Fight_Club": "搏击俱乐部",
    "Se7en_(film)": "七宗罪",
    "The_Game": "心理游戏",
    "Panic_Room": "战栗空间",
    "Zodiac_(film)": "十二宫",
    "The_Social_Network": "社交网络",
    "The_Girl_with_the_Dragon_Tattoo_(2011_film)": "龙纹身的女孩",
    "Gone_Girl_(film)": "消失的爱人",
    "Benjamin_Button": "本杰明·巴顿奇事",
    "The_Curious_Case_of_Benjamin_Button_(film)": "本杰明·巴顿奇事",
    "Moneyball_(film)": "点球成金",
    "World_Trade_Center_(film)": "世贸中心",
    "United_93_(film)": "93号航班",
    "The_Postman_(film)": "未来水世界",
    "Waterworld": "未来水世界",
    "The_Rock_(film)": "石破天惊",
    "Con_Air": "空中监狱",
    "Face/Off": "变脸",
    "Broken_Arrow": "断箭",
    "Mission:_Impossible_II": "碟中谍2",
    "Mission:_Impossible_III": "碟中谍3",
    "Top_Gun": "壮志凌云",
    "Days_of_Thunder": "雷霆壮志",
    "Jerry_Muire": "甜心先生",
    "A_Few_Good_Men": "义海雄风",
    "The_Firm_(1993_film)": "糖衣陷阱",
    "Interview_with_the_Vampire_(film)": "夜访吸血鬼",
    "Queen_of_the_Damned": "吸血鬼女王",
    "Blade": "刀锋战士",
    "Underworld": "黑夜传说",
    "Resident_Evil_(film)": "生化危机",
    "Silent_Hill_(film)": "寂静岭",
    "Doom": "毁灭战士",
    "Hitman": "杀手代号47",
    "Max_Payne": "马克思·佩恩",
    "Need_for_Speed": "极品飞车",
    "Assassin's_Creed": "刺客信条",
    "Prince_of_Persia:_The_Sands_of_Time_(film)": "波斯王子：时之刃",
    "Tomb_Raider": "古墓丽影",
    "Street_Fighter": "街头霸王",
    "Mortal_Kombat": "格斗之王",
    "DOA:_Dead_or_Alive": "生死格斗",
    "Tekken": "铁拳",

    # === 纪录片/音乐 ===
    "March_of_the_Penguins": "帝企鹅日记",
    "An_Inconvenient_Truth": "难以忽视的真相",
    "Fahrenheit_9/11": "华氏911",
    "Supersize_Me": "超码的我",
    "Man_on_Wire": "走钢丝的人",
    "Senna_(film)": "塞纳",
    "Baraka_(film)": "巴拉卡",
    "Pina_(film)": "皮娜",
    "Amy": "艾米",
    "Searching_for_Sugar_Man": "寻找小糖人",
    "The_Cove": "海豚湾",
    "Blackfish": "黑鲸",
    "Free_Solo": "徒手攀岩",

    # === 日韩电影 ===
    "Battle_Royale_(film)": "大逃杀",
    "Ringu": "午夜凶铃",
    "Ju-On": "咒怨",
    "Dark_Water": "鬼水怪谈",
    "Audition": "切肤之爱",
    "Ichi_the_Killer": "杀手阿一",
    "Oldboy": "老男孩",
    "Sympathy_for_Mr._Vengeance": "我要复仇",
    "Lady_Vengeance": "亲切的金子",
    "Memories_of_Murder": "杀人回忆",
    "The_Host_(2006_film)": "汉江怪物",
    "Mother": "母亲",
    "Parasite": "寄生虫",
    "Train_to_Busan": "釜山行",
    "Snowpiercer": "雪国列车",
    "Okja": "玉子",
    "Burning": "燃烧",
    "A_Tale_of_Two_Sisters": "蔷花红莲",
    "The_Wailing": "哭声",
    "Spirited_Away": "千与千寻",
    "Howl's_Moving_Castle_(film)": "哈尔的移动城堡",
    "Princess_Mononoke": "幽灵公主",
    "My_Neighbor_Totoro": "龙猫",
    "Grave_of_the_Fireflies": "萤火虫之墓",
    "Kiki's_Delivery_Service": "魔女宅急便",
    "Porco_Rosso": "红猪",
    "The_Wind_Rises": "起风了",
    "Ponyo": "悬崖上的金鱼姬",
    "Arrietty": "借东西的小人阿莉埃蒂",
    "From_Up_on_Poppy_Hill": "虞美人盛开的山坡",
    "Tales_from_Earthsea": "地海传说",
    "Paprika": "红辣椒",
    "Perfect_Blue": "未麻的部屋",
    "Akira": "阿基拉",
    "Ghost_in_the_Shell": "攻壳机动队",
    "Cowboy_Bebop:_The_Movie": "星际牛仔：天国之门",
    "Ninja_Scroll": "兽兵卫忍风帖",
    "Vampire_Hunter_D": "吸血鬼猎人D",
    "Fist_of_the_North_Star_(1986_film)": "北斗神拳",
    "Dragon_Ball_Z:_Broly_-_The_Legend": "龙珠Z：传说中的超赛",

    # === 港台/华语电影 ===
    "Infernal_Affairs": "无间道",
    "In_the_Mood_for_Love": "花样年华",
    "Chungking_Express": "重庆森林",
    "Happy_Together_(1997_film)": "春光乍泄",
    "2046_(film)": "2046",
    "Ashes_of_Time": "东邪西毒",
    "Crouching_Tiger,_Hidden_Dragon": "卧虎藏龙",
    "Hero": "英雄",
    "House_of_Flying_Daggers": "十面埋伏",
    "Curse_of_the_Golden_Flower": "满城尽带黄金甲",
    "Red_Cliff_(film)": "赤壁",
    "Ip_Man_(film)": "叶问",
    "Kung_Fu_Hustle": "功夫",
    "Shaolin_Soccer": "少林足球",
    "The_God_of_Cookery": "食神",
    "A_Chinese_Odyssey": "大话西游",
    "Farewell_My_Concubine_(film)": "霸王别姬",
    "Raise_the_Red_Lantern": "大红灯笼高高挂",
    "To_Live": "活着",
    "Ju_Dou": "菊豆",
    "The_Road_Home": "我的父亲母亲",
    "Not_One_Less": "一个都不能少",
    "Happy_Time": "幸福时光",
    "Erta_Ale": "一个陌生女人的来信",
    "Lust,_Caution": "色，戒",
    "The_Banquet": "夜宴",
    "Perhaps_Love": "如果·爱",
    "Comrades:_Almost_a_Love_Story": "甜蜜蜜",
    "Infernal_Affairs_(film)": "无间道",
    "A_Better_Tomorrow": "英雄本色",
    "The_Killer": "喋血双雄",
    "Hard_Boiled": "辣手神探",
    "City_on_Fire": "龙虎风云",
    "Full_Contact": "侠盗高飞",
    "Breaking_News": "大事件",
    "Election": "黑社会",
    "Election_2": "黑社会2：以和为贵",
    "Exiled": "放·逐",
    "Drug_War": "毒战",
    "PTU": "PTU",
    "The_Mission_(1986_film)": "暗战",
    "Running_Out_of_Time": "暗战",
    "Too_Many_Cooks": "买凶拍人",
    "Infernal_Affairs_II": "无间道2",
    "Infernal_Affairs_III": "无间道3",

    # === 印度电影 ===
    "Three_Idiots": "三傻大闹宝莱坞",
    "Lagaan": "印度往事",
    "Dangal": "摔跤吧！爸爸",
    "PK": "我的个神啊",
    "Baahubali": "巴霍巴利王",
    "Slumdog_Millionaire": "贫民窟的百万富翁",
    "The_Lunchbox": "午餐盒",
    "Rang_De_Basanti": "芭萨提的颜色",
    "Dilwale_Dulhania_Le_Jayenge": "勇夺芳心",
    "My_Name_Is_Khan": "我的名字叫可汗",
    "Zindagi_Na_Milegi_Dobara": "人生不再重来",
    "Queen": "女皇",
    "Barfi": "巴菲的奇妙命运",
    "Andhadhun": "调音师",
    "Gully_Boy": "街角少年",

    # === 其他常见电影 ===
    "Amelie": "天使爱美丽",
    "The_Intouchables": "触不可及",
    "La_Haine": "仇恨",
    "Persepolis_(film)": "我在伊朗长大",
    "The_Artist_(film)": "艺术家",
    "Amour_(2012_film)": "爱",
    "The_Pianist_(2002_film)": "钢琴家",
    "Downfall_(2004_film)": "帝国的毁灭",
    "The_Lives_of_Others": "窃听风暴",
    "Run_Lola_Run": "罗拉快跑",
    "Das_Boot": "从海底出击",
    "The_NeverEnding_Story_(film)": "大魔域",
    "Wings_of_Desire": "柏林苍穹下",
    "Fitzcarraldo": "陆上行舟",
    "Aguirre,_the_Wrath_of_God": "阿基尔，上帝的愤怒",
    "Nosferatu": "诺斯费拉图",
    "M": "M就是凶手",
    "The_Cabinet_of_Dr._Caligari": "卡里加里博士的小屋",
    "Metropolis_(1927_film)": "大都会",
    "Pan's_Labyrinth": "潘神的迷宫",
    "The_Sea_Inside": "深海长眠",
    "Volver": "回归",
    "All_About_My_Mother": "关于我母亲的一切",
    "Talk_to_Her": "对她说",
    "Bad_Education_(film)": "不良教育",
    "Broken_Embraces": "破碎的拥抱",
    "The_Skin_I_Live_In": "吾栖之肤",
    "Y_Tu_Mama_Tambien": "你妈妈也一样",
    "Amores_Perros": "爱情是狗娘",
    "Biutiful": "美错",
    "The_Revenant": "荒野猎人",
    "Birdman": "鸟人",
    "Babel_(film)": "通天塔",
    "21_Grams_(film)": "21克",
    "Roma": "罗马",
    "Gravity": "地心引力",
    "Children_of_Men": "人类之子",
    "Harry_Potter_and_the_Philosopher's_Stone_(film)": "哈利·波特与魔法石",
    "Harry_Potter_and_the_Chamber_of_Secrets_(film)": "哈利·波特与密室",
    "Harry_Potter_and_the_Prisoner_of_Azkaban_(film)": "哈利·波特与阿兹卡班的囚徒",
    "Harry_Potter_and_the_Goblet_of_Fire_(film)": "哈利·波特与火焰杯",
    "Harry_Potter_and_the_Order_of_the_Phoenix_(film)": "哈利·波特与凤凰社",
    "Harry_Potter_and_the_Half-Blood_Prince_(film)": "哈利·波特与混血王子",
    "The_Hunger_Games_(film)": "饥饿游戏",
    "The_Dark_Knight_(film)": "蝙蝠侠：黑暗骑士",
    "Man_of_Steel_(film)": "超人：钢铁之躯",
    "The_Avengers_(2012_film)": "复仇者联盟",
    "Kick-Ass_(film)": "海扁王",
    "Scott_Pilgrim_vs._the_World_(film)": "歪小子斯科特对抗全世界",
    "Kingsman:_The_Secret_Service": "王牌特工：特工学院",
    "Sherlock_Holmes_(2009_film)": "大侦探福尔摩斯",
    "The_Tourist_(2010_film)": "致命伴旅",
    "Salt_(2010_film)": "特工绍特",
    "Wanted_(2008_film)": "通缉令",
    "Red_(2010_film)": "赤焰战场",
    "The_Expendables_(2010_film)": "敢死队",
    "Rambo_(2008_film)": "第一滴血4",
    "Rocky_Balboa_(film)": "洛奇6",
    "Rocky": "洛奇",
    "Raging_Bull": "愤怒的公牛",
    "GoodFellas": "好家伙",
    "Casino": "赌城风云",
    "The_Irishman": "爱尔兰人",
    "Once_Upon_a_Time_in_America": "美国往事",
    "Once_Upon_a_Time_in_the_West": "西部往事",
    "The_Good,_the_Bad_and_the_Ugly": "黄金三镖客",
    "A_Fistful_of_Dollars": "荒野大镖客",
    "For_a_Few_Dollars_More": "黄昏双镖客",
    "Django_Unchained": "被解救的姜戈",
    "Inglourious_Basterds": "无耻混蛋",
    "Kill_Bill:_Vol._1": "杀死比尔",
    "Kill_Bill:_Vol._2": "杀死比尔2",
    "Jackie_Brown_(film)": "危险关系",
    "Death_Proof": "死亡证据",
    "Reservoir_Dogs": "落水狗",
    "True_Romance": "致命浪漫",
    "Natural_Born_Killers": "天生杀人狂",
    "The_Hateful_Eight": "八恶人",
    "Once_Upon_a_Time_in_Hollywood": "好莱坞往事",
    "Interstellar": "星际穿越",
    "The_Great_Gatsby_(2013_film)": "了不起的盖茨比",
    "Django_Unchained_(film)": "被解救的姜戈",
    "Life_of_Pi_(film)": "少年派的奇幻漂流",
    "Slumdog_Millionaire_(film)": "贫民窟的百万富翁",
    "The_King's_Speech": "国王的演讲",
    "The_Artist_(film)": "艺术家",
    "Argo_(2012_film)": "逃离德黑兰",
    "Zero_Dark_Thirty": "猎杀本·拉登",
    "The_Hurt_Locker": "拆弹部队",
    "12_Years_a_Slave": "为奴十二年",
    "Selma": "塞尔玛",
    "The_Butler": "白宫管家",
    "Hidden_Figures": "隐藏人物",
    "Get_Out": "逃出绝命镇",
    "Us": "我们",
    "Black_Panther": "黑豹",
    "Spider-Man:_Into_the_Spider-Verse": "蜘蛛侠：平行宇宙",
    "Coco_(film)": "寻梦环游记",
    "Inside_Out_(film)": "头脑特工队",
    "Zootopia_(film)": "疯狂动物城",
    "Frozen_(film)": "冰雪奇缘",
    "Tangled_(film)": "魔发奇缘",
    "Wreck-It_Ralph_(film)": "无敌破坏王",
    "Big_Hero_6_(film)": "超能陆战队",
    "Moana_(film)": "海洋奇缘",
    "Toy_Story_(film)": "玩具总动员",
    "Toy_Story_2": "玩具总动员2",
    "Toy_Story_3": "玩具总动员3",
    "Monsters,_Inc._(film)": "怪兽电力公司",
    "Finding_Nemo_(film)": "海底总动员",
    "The_Incredibles_(film)": "超人总动员",
    "Ratatouille_(film)": "美食总动员",
    "WALL-E_(film)": "机器人总动员",
    "Up_(2009_film)": "飞屋环游记",
    "How_to_Train_Your_Dragon_(film)": "驯龙高手",
    "Kung_Fu_Panda_(film)": "功夫熊猫",
    "Madagascar_(2005_film)": "马达加斯加",
    "Shrek_(film)": "怪物史瑞克",
    "Ice_Age_(2002_film)": "冰河世纪",
    "Despicable_Me_(film)": "神偷奶爸",

    # === 补充：更多电影 ===
    "Gandhi_(film)": "甘地传",
    "Schindler's_List_(film)": "辛德勒的名单",
    "Philadelphia_(film)": "费城故事",
    "Milk_(film)": "米尔克",
    "Capote_(film)": "卡波特",
    "The_Iron_Lady_(film)": "铁娘子",
    "The_Queen_(film)": "女王",
    "The_King's_Speech_(film)": "国王的演讲",
    "Lincoln": "林肯",
    "Nixon_(film)": "尼克松",
    "JFK_(film)": "刺杀肯尼迪",
    "Thirteen_Days_(film)": "惊爆十三天",
    "All_the_President's_Men_(film)": "总统班底",
    "Frost/Nixon": "对话尼克松",
    "The_Ides_of_March_(film)": "总统杀局",
    "Primary_Colors_(film)": "原色",
    "W._(film)": "小布什传",
    "Game_Change_(film)": "规则改变",
    "Recount_(film)": "选票风波",
    "The_Social_Network_(film)": "社交网络",
    "Moneyball_(film)": "点球成金",
    "Steve_Jobs": "史蒂夫·乔布斯",
    "The_Great_Hack": "隐私大盗",
    "The_Sessions_(film)": "亲密治疗",
    "The_Impossible_(2012_film)": "海啸奇迹",
    "127_Hours": "127小时",
    "Into_the_Wild_(film)": "荒野生存",
    "The_Road_(2009_film)": "末日危途",
    "The_Book_of_Eli": "艾利之书",
    "I_Am_Legend_(film)": "我是传奇",
    "World_War_Z": "僵尸世界大战",
    "28_Days_Later": "惊变28天",
    "28_Weeks_Later": "惊变28周",
    "Resident_Evil_(film)": "生化危机",
    "Resident_Evil:_Apocalypse": "生化危机2：启示录",
    "Resident_Evil:_Extinction": "生化危机3：灭绝",
    "Resident_Evil:_Afterlife": "生化危机4：战神再生",
    "Resident_Evil:_Retribution": "生化危机5：惩罚",
    "Resident_Evil:_The_Final_Chapter": "生化危机：终章",
    "Underworld_(film)": "黑夜传说",
    "Underworld:_Evolution": "黑夜传说2：进化",
    "Underworld:_Rise_of_the_Lycans": "黑夜传说前传：狼族再起",
    "Blade_(film)": "刀锋战士",
    "Blade_II": "刀锋战士2",
    "Blade:_Trinity": "刀锋战士3",
    "The_Crow_(film)": "乌鸦",
    "Constantine_(film)": "康斯坦丁",
    "Ghost_Rider_(film)": "恶灵骑士",
    "Spawn": "再生侠",
    "Judge_Dredd_(film)": "特警判官",
    "Dredd": "新特警判德",
    "RoboCop": "机械战警",
    "Total_Recall_(1990_film)": "全面回忆",
    "Running_Man": "过关斩将",
    "Demolition_Man_(film)": "越空狂龙",
    "The_5th_Element": "第五元素",
    "Lock_Up_(film)": "破茧威龙",
    "Cobra_(1986_film)": "眼镜蛇",
    "Over_the_Top_(film)": "超越巅峰",
    "Rambo:_First_Blood_Part_II": "第一滴血2",
    "Rambo_III": "第一滴血3",
    "First_Blood": "第一滴血",
    "Cliffhanger_(film)": "绝岭雄风",
    "Daylight_(film)": "龙出生天",
    "Driven": "生死极速",
    "Get_Smart_(film)": "糊涂侦探",
    "The_Spy_Next_Door": "邻家特工",
    "Rush_Hour_(1998_film)": "尖峰时刻",
    "Rush_Hour_2": "尖峰时刻2",
    "Shanghai_Noon": "上海正午",
    "Shanghai_Knights": "上海骑士",
    "The_Karate_Kid": "龙威小子",
    "The_Karate_Kid_(2010_film)": "功夫梦",
    "Beverly_Hills_Cop": "比佛利山超级警探",
    "Beverly_Hills_Cop_II": "比佛利山超级警探2",
    "48_Hrs.": "48小时",
    "Another_48_Hrs.": "又一个48小时",
    "Lethal_Weapon": "致命武器",
    "Lethal_Weapon_2": "致命武器2",
    "Lethal_Weapon_3": "致命武器3",
    "Lethal_Weapon_4": "致命武器4",
    "Die_Hard": "虎胆龙威",
    "Die_Hard_2": "虎胆龙威2",
    "Die_Hard:_With_a_Vengeance": "虎胆龙威3",
    "Live_Free_or_Die_Hard": "虎胆龙威4",
    "Predator": "铁血战士",
    "Predator_2": "铁血战士2",
    "Commando": "独闯龙潭",
    "The_Running_Man_(film)": "过关斩将",
    "Total_Recall_(1990_film)": "全面回忆",
    "Kindergarten_Cop": "幼儿园警探",
    "Twins": "龙兄鼠弟",
    "Junior": "威龙二世",
    "Jingle_All_the_Way": "一路响叮当",
    "Conan_the_Barbarian_(1982_film)": "野蛮人柯南",
    "Conan_the_Destroyer": "毁灭者柯南",
    "Red_Sonja": "红衣女郎",
    "Hercules_(1958_film)": "大力神",
    "Jason_and_the_Argonauts": "伊阿宋和阿耳戈英雄",
    "Clash_of_the_Titans_(1981_film)": "诸神之战",
    "The_Scorpion_King_(film)": "蝎子王",
    "The_Mummy_Returns": "木乃伊归来",
    "The_Mummy:_Tomb_of_the_Dragon_Emperor": "木乃伊3：龙帝之墓",
    "Tomb_Raider_(film)": "古墓丽影",
    "Lara_Croft:_Tomb_Raider_–_The_Cradle_of_Life": "古墓丽影2",
    "National_Treasure:_Book_of_Secrets": "国家宝藏2",
    "Pirates_of_the_Caribbean:_The_Curse_of_the_Black_Pearl": "加勒比海盗",
    "Pirates_of_the_Caribbean:_Dead_Man's_Chest": "加勒比海盗2：聚魂棺",
    "Pirates_of_the_Caribbean:_At_World's_End": "加勒比海盗3：世界的尽头",
    "Pirates_of_the_Caribbean:_On_Stranger_Tides": "加勒比海盗4：惊涛怪浪",
    "Alice_in_Wonderland_(2010_film)": "爱丽丝梦游仙境",
    "Maleficent": "沉睡魔咒",
    "Cinderella_(2015_film)": "灰姑娘",
    "The_Jungle_Book_(2016_film)": "奇幻森林",
    "Beauty_and_the_Beast_(2017_film)": "美女与野兽",
    "Aladdin_(2019_film)": "阿拉丁",
    "The_Lion_King_(2019_film)": "狮子王",
    "Dumbo_(2019_film)": "小飞象",
    "Mulan_(2020_film)": "花木兰",
}


def main():
    lex_path = os.path.join(os.path.dirname(__file__), "..", "data", "kg", "db15k_movie_lexicon.json")
    lex_path = os.path.abspath(lex_path)
    entity2id_path = os.path.join(os.path.dirname(__file__), "..", "..", "MMKG_item", "datasets", "DB15K", "entity2id.txt")
    entity2id_path = os.path.abspath(entity2id_path)

    # 读取词典
    with open(lex_path, encoding="utf-8") as f:
        data = json.load(f)
    alias_map = data["alias_to_entity"]

    # 读取 entity2id，获取所有实体短名
    all_entity_shorts = set()
    with open(entity2id_path, encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) == 2:
                uri = parts[0]
                short = uri.rstrip(">").rsplit("/", 1)[-1]
                all_entity_shorts.add(short)

    # 反向索引：entity -> 已有别名
    entity_to_aliases = {}
    for alias, entity in alias_map.items():
        entity_to_aliases.setdefault(entity, []).append(alias)

    lexicon_entities = set(alias_map.values())
    print(f"entity2id 总实体数: {len(all_entity_shorts)}")
    print(f"词典中唯一实体数: {len(lexicon_entities)}")

    # ---- 第一步：把 KNOWN_ZH 中不在词典里的实体加入词典 ----
    added_to_lexicon = 0
    for entity, zh_name in KNOWN_ZH.items():
        if entity in lexicon_entities:
            continue  # 已在词典中
        if entity not in all_entity_shorts:
            continue  # 不在 DB15K 中

        # 添加到词典：英文变体 + 中文别名
        alias_map[entity.lower()] = entity
        alias_map[entity.lower().replace("_", " ")] = entity
        alias_map[zh_name] = entity
        entity_to_aliases.setdefault(entity, []).append(entity.lower())
        entity_to_aliases.setdefault(entity, []).append(zh_name)
        lexicon_entities.add(entity)
        added_to_lexicon += 1

    print(f"新增词典实体（不带后缀的知名电影）: {added_to_lexicon}")

    # ---- 第二步：为所有词典实体添加中文别名 ----
    added_zh = 0
    already_has_zh = 0
    no_translation = 0

    for entity in sorted(lexicon_entities):
        existing = entity_to_aliases.get(entity, [])
        has_zh = any("一" <= c <= "鿿" for a in existing for c in a)
        if has_zh:
            already_has_zh += 1
            continue

        zh_name = KNOWN_ZH.get(entity)
        if not zh_name:
            base = entity.replace("_(film)", "").replace("_(movie)", "")
            zh_name = KNOWN_ZH.get(base)

        if zh_name:
            alias_map[zh_name] = entity
            added_zh += 1
        else:
            no_translation += 1

    # 更新元数据
    data["alias_count"] = len(alias_map)
    data["zh_alias_count"] = sum(1 for k in alias_map if any("一" <= c <= "鿿" for c in k))
    data["movie_entity_count"] = len(lexicon_entities)

    with open(lex_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\n=== 结果 ===")
    print(f"新增中文别名: {added_zh}")
    print(f"已有中文别名: {already_has_zh}")
    print(f"未找到翻译: {no_translation}")
    print(f"词典总实体数: {len(lexicon_entities)}")
    print(f"总别名数: {len(alias_map)}")
    print(f"中文别名总数: {data['zh_alias_count']}")


if __name__ == "__main__":
    main()
